apiVersion: v1
kind: Service
metadata:
  name: hellogo
  namespace: dummy
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081
  selector:
    k8s-app: hellogo
  type: ClusterIP
