apiVersion: v1
kind: Service
metadata:
  name: hellonode
  namespace: {{.NAMESPACE}}
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081
  selector:
    k8s-app: hellonode
  type: ClusterIP
