apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hellonode
  namespace: dummy
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: hellonode
  template:
    metadata:
      labels:
        k8s-app: hellonode
    spec:
      containers:
      - name: hellonode
        image: gcr.io/dummy-143017/hellonode:v1
        ports:
        - containerPort: 8080
