apiVersion: v1
kind: Service
metadata:
  name: hellonode-svc
  labels:
    app: hellonode
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    nodePort: 30001
  selector:
    app: hellonode
