apiVersion: v1
kind: Service
metadata:
  name: hellonode
  namespace: dummy
  # labels:
    # app: hellonode
    # k8s-app: hellonode
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    k8s-app: hellonode
    # app: hellonode
  type: LoadBalancer
