apiVersion: v1
kind: Service
metadata:
  name: main-ingress
  namespace: {{.NAMESPACE}}
spec:
  ports:
  - name: http
    nodePort: {{.INGRESS_HTTP_PORT}}
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    nodePort: {{.INGRESS_HTTPS_PORT}}
    protocol: TCP
    port: 443
    targetPort: 443
  selector:
    k8s-app: main-ingress-lb
  sessionAffinity: None
  type: LoadBalancer
