apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: main-ingress
  namespace: {{.NAMESPACE}}
spec:
  tls:
    - hosts:
      - {{.INGRESS_HOSTNAME}}
      secretName: server-cert
  rules:
  - host: {{.INGRESS_HOSTNAME}}
    http:
      paths:
      - path: /hellogo
        backend:
          serviceName: hellogo
          servicePort: 8080
      - path: /hellonode
        backend:
          serviceName: hellonode
          servicePort: 8081
