apiVersion: v1
kind: Service
metadata:
  name: main-ingress
  namespace: dummy
spec:
  ports:
  - name: http
    nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: main-ingress-lb
  sessionAffinity: None
  type: LoadBalancer
