etcd:
  image: gcr.io/google_containers/etcd:2.2.1
  net: host
  command: [ '/usr/local/bin/etcd',
             '--addr=127.0.0.1:4001',
             '--bind-addr=0.0.0.0:4001',
             '--data-dir=/var/etcd/data']

kube-master:
  image: gcr.io/google_containers/hyperkube:v1.2.5
  net: host
  pid: host
  privileged: true
  volumes:
    - /:/rootfs:ro
    - /sys:/sys:ro
    - /dev:/dev
    - /var/lib/docker/:/var/lib/docker:rw
    - /var/lib/kubelet/:/var/lib/kubelet:rw
    - /var/run:/var/run:rw
  command: ['/hyperkube',
            'kubelet',
            '--containerized',
            '--hostname-override=127.0.0.1',
            '--address=0.0.0.0',
            '--api-servers=http://localhost:8080',
            '--config=/etc/kubernetes/manifests-multi',
            '--cluster-dns=10.0.0.10',
            '--cluster-domain=internal',
            '--maximum-dead-containers=10',
            '--allow-privileged=true',
            '--v=2']
