apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hellogo
  namespace: dummy
spec:
  replicas: {{.HELLOGO_REPLICAS}}
  selector:
    matchLabels:
      k8s-app: hellogo
  template:
    metadata:
      labels:
        k8s-app: hellogo
    spec:
      containers:
      - name: hellogo
        image: gcr.io/dummy-143017/hellogo:v1
        ports:
        - containerPort: 8080
      - name: hellonode
        image: gcr.io/dummy-143017/hellonode:v1
        ports:
        - containerPort: 8081
